# Generated by Django 5.2.15 on 2026-06-21 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scan',
            name='current_module',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='scan',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='scan',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scanmoduleresult',
            name='module',
            field=models.CharField(choices=[('naabu', 'Port Tarama'), ('subdomain', 'Subdomain'), ('wayback', 'Wayback'), ('httpx', 'HTTPX'), ('nuclei', 'Nuclei'), ('dnsx', 'DNS Kayıtları'), ('katana', 'Web Crawl')], max_length=32),
        ),
    ]
