# Generated by Django 5.2.15 on 2026-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='scanmoduleresult',
            name='module',
            field=models.CharField(choices=[('naabu', 'Port Tarama'), ('subdomain', 'Subdomain'), ('wayback', 'Wayback'), ('httpx', 'HTTPX'), ('nuclei', 'Nuclei'), ('dnsx', 'DNS Kayıtları'), ('katana', 'Web Crawl'), ('nmap', 'Nmap Servis')], max_length=32),
        ),
    ]
