# Generated by Django 5.2.15 on 2026-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_notifications_scan_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('awaiting_subdomains', 'Alt Alan Seçimi'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanmoduleresult',
            name='module',
            field=models.CharField(choices=[('naabu', 'Port Tarama'), ('subdomain', 'Subdomain'), ('wayback', 'Wayback'), ('httpx', 'HTTPX'), ('nuclei', 'Nuclei'), ('dnsx', 'DNS Kayıtları'), ('katana', 'Web Crawl'), ('nmap', 'Nmap Servis'), ('whatweb', 'WhatWeb Teknoloji')], max_length=32),
        ),
    ]
